### PR TITLE
add within-target-par section

### PR DESCRIPTION
**Pull request by pat-s**
# Summary

- Devote an extra H2 section to the topic
- Introduce sub-sections
	- General notes
	- Execution on a single machine
	- Execution on a HPC

# Related GitHub issues and pull requests

- Ref: #69

# Checklist

- [x] I have read this repository's [code of conduct](https://github.com/ropensci/drake-manual/blob/master/CONDUCT.md), and I agree to follow its rules.
- [x] I have listed any substantial changes in the [development news](https://github.com/ropenscilabs/drake-manual/blob/master/NEWS.md).
- [x] This pull request is ready for review.
- [] I think this pull request is ready to merge.

### CODE REVIEW

**Comment by pat-s** [comment]
@wlandau 	It would be great if there was an automated PR preview of the book via [Netlify](https://www.netlify.com/tags/deploy-previews/).
See also [here](https://github.com/mlr-org/mlr) for an example which previews the pkgdown page on every PR.

**Comment by wlandau** [comment]
Thanks, @pat-s. I will look at #70 and #69 when I can carve out some quality time. Right now I am doing quick wrap-up from the Chicago R Unconference.

**Comment by wlandau** [comment]
Also, re Netlify: I tried that at one point, but I could not quite get it working. I did not have [`mlr`](https://github.com/mlr-org/mlr) as a reference at the time. I will try again (#71). Thanks!

**Comment by wlandau** [comment]
Thank you for the suggestions, @pat-s. Your writing has clarified my thinking, and I now believe we should try something different for this section. Rather than touching on many pitfalls and workarounds, I now think we should focus exclusively on `future.callr`, which means getting rid of the `mclapply()` stuff I wrote at the top (though maybe https://github.com/ropensci/drake/issues/675#issuecomment-458222414 still deserves a quick mention). `make(prework = quote(future::plan(future.callr::callr, workers = 4L)))` should generalize to `parallelism = "loop"` locally and `parallelism = "clustermq"` on HPC. For `future`-based parallelism, I think we need something like `make(parallelism = "future", prework = quote(future::plan(list(tweak(future.batchtools::batchtools_slurm, template = "your_template.tmpl"), tweak(future.callr, workers = 4L)))))`.

Do you intend to continue with the writing? If not, please let me know.

**Comment by pat-s** [comment]
> make(prework = quote(future::plan(future.callr::callr, workers = 4L))) should generalize to parallelism = "loop" locally and parallelism = "clustermq" on HPC. For future-based parallelism, I think we need something like make(parallelism = "future", prework = quote(future::plan(list(tweak(future.batchtools::batchtools_slurm, template = "your_template.tmpl"), tweak(future.callr, workers = 4L))))).

Makes sense and would make a lot easier for the user.

> Do you intend to continue with the writing? If not, please let me know.

Sure! Just let me know how you want to structure it so that we do not duplicate work. I can pick up from the point at which you set the section structure and fill it with content.
But I am also not upset if you want to write it on your own to stay within your thoughts. My writing already helped to start the process and that's good.

Just let me know :)

**Comment by wlandau** [comment]
I am closing this PR because I think https://github.com/ropenscilabs/drake-manual/commit/8816590c061c931e85979ff8704613119d7f1cf8 is what we need. Sorry I did not literally insert your writing, @pat-s. I still found it useful.

**Pull request closed without merging**
