### PR TITLE
Draft on workflow data frames

### LINKED ISSUE #5: Dedicated vignette on wildcard templating
Ref: https://github.com/ropensci/drake/issues/388. cc @lorenzwalthert

### PR DESCRIPTION
**Pull request by lorenzwalthert**
Intended to close #5. After going back and forth, I figured that using the GSP example would be complicating things more than the need to be. 
I decided to use simple base R functions that the reader should be familiar with. I think this should make the chapter an easier read, hope this is ok for you. 

Also, I have a question regarding `plan_analyses()` and `plan_summaries()`: I found them to be very confusing at first and I think `evaluate_plan()` offers a much more generic and simpler API. Are those planned to be depreciated at some point? I nevertheless introduced them before I introduced `evaluate_plan()`. Should we switch the order? 

Any thought appreciated, and sorry you had to wait forever 😩

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
Also i did not know to nulver you want the chapter to have, do. I just opted for the last one. But I think that's not really where it should go. Happy to adapt the PR and the numbering in this PR according to your preference.

**Comment by wlandau** [comment]
Thank you, Lorenz! This is a huge help, and I really appreciate it. I will read it closely as soon as I can. Please feel free to add yourself as an author in the manual's `DESCRIPTION` file.

Re: `plan_analyses()` and `plan_summaries()`, you bring up a good point. Those functions made sense at the time, but I agree, they are more awkward and narrow than `evaluate_plan()`. I am not sure about deprecating them, but we can certainly put `evaluate_plan()` front and center in the documentation and talk about `plan_analyses()` and `plan_summaries()` as an afterthought.

**Comment by lorenzwalthert** [comment]
Ok, cool, thanks for the answer. I just adapted the PR according to your suggestions, i.e. put the `evaluate_plan()` first. Also, I added a sub-chapter with a little comparison.

Also, do I need to build the book locally and commit html? If you are interested, we can also set up deployment via netlify / travis, I just looked into it for my own [blogdown blog](http://lorenzwalthert.netlify.com/posts/getting-up-and-running-with-blogdown-netlify-and-travis/). It would be similar to the https://style.tidyverse.org page.

**Comment by wlandau** [comment]
Your new chapter is a really nice start! It is giving me a lot of new ideas about how to explain plans, so I may take a stab the writing too after you are satisfied and ready to merge. A few comments so far:

- Right now, I think your writeup deserves a place right after the intro. It's simple and concise, and it covers fundamental material. 
- The term "workflow plan data frame" is a mouthful, and in conversation, the term "`drake` plan" has started to catch on. No need to worry about it now, but I think I might go back and make the switch at some point.
- In the first section ("What is a workflow plan data frame?") I would elaborate a little more on the role and purpose of the plan. Some possible points of emphasis:
    - The purpose of the plan is to declare the data objects and files you are going to produce later on.
    - You can declare targets in any order and `drake` will figure out the order of execution.
    - Creating the plan does not run any of the commands.
    - Maybe demo a `make()`.
- I really like how you tie things back to `Make` and `remake`. Maybe we can introduce that history in a new section on "Why make a plan?", and maybe this section should be at the very top. We can begin with the general problem of not repeating up-to-date work, and we can describe how `Makefile`s were so important to the solution. Then, we could argue that `drake`'s workflow plans are the R-focused answer to the need for a `Makefile` for data analysis, with these main advantages:
    1. Coding up a big data frame is easier than typing a `Makefile` all by hand, and
    2. Dependencies among targets are detected with code analysis, so you don't need to declare them explicitly.

**Comment by lorenzwalthert** [comment]
Ok, so I think the renaming / numbering could be a separate PR then, just leaving nr 2 out for now. Since that will heavily affect the git stats (additions and deletion), do you want to do it yourself? I can do it if you want.

**Comment by lorenzwalthert** [comment]
> [...] may take a stab the writing too after you are satisfied and ready to merge [...].

Sure

**Comment by lorenzwalthert** [comment]
Also, when referring to the package, should I use code font or not?

**Comment by lorenzwalthert** [comment]
> The term "workflow plan data frame" is a mouthful, and in conversation, the term "drake plan" has started to catch on. No need to worry about it now, but I think I might go back and make the switch at some point.

Ok, I leave it for now.

**Comment by lorenzwalthert** [comment]
> [...] I really like how you tie things back to Make and remake [...]

I picked that up, however, I think it naturally fits into the third section. If we start with this before introducing targets and build commands, I think it's confusing. You can obviously always change it later, but I'd suggest not to put that paragraph first.

**Comment by wlandau** [comment]
Thanks for the edits, Lorenz. I think the chapter is ready to merge, and I plan to continue writing and editing going forward.

So far, I have been building the book and committing the html, but I would very much prefer to deploy with netlify and travis. Related: #2.

**Comment by lorenzwalthert** [comment]
Ok, so I assume that you build the page and push the html for now (I have not done that). Also, the chapter is currently chapter 14 and not chapter 2. I let you do the renaming then.

**Pull request merged**
