### PR TITLE
Test PR

### PR DESCRIPTION
**Pull request by wlandau**
Just trying to see if the Netlify preview of a pull request can show up now that https://drake-manual.netlify.com/ is already successfully deployed.

### CODE REVIEW

**Comment by wlandau** [comment]
Nope, that's not what I want. The Netflify deploy preview does not wait for Travis.



And that means it can't use the `_book` directory, which probably explains why https://deploy-preview-16--drake-manual.netlify.com/ has an error:



So is it even worth trying to use both Travis and Netlify? Maybe we can't have both a remote `render_book()` and previews of pull requests. cc @lorenzwalthert.

**Comment by lorenzwalthert** [comment]
Well the reason why the preview does not work is because we don't commit html files. The build command on netlify is hugo, not blogdown. Thats the reason we are using Travis: to run blogdown. Looking into this later.

**Comment by lorenzwalthert** [comment]
Sorry I meant bookdown not blogdown.

**Comment by wlandau** [comment]
Hmm... then it looks like we have to choose between remote builds and PR previews, at least for now. And I think remote builds add the most convenience. Netlify was definitely worth a shot, and I really appreciate your help along the way.

**Pull request closed without merging**
